/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppNotesIndexRouteImport } from './routes/_app/notes.index'
import { Route as AppSettingsVocabularyRouteImport } from './routes/_app/settings/vocabulary'
import { Route as AppSettingsSnippetsRouteImport } from './routes/_app/settings/snippets'
import { Route as AppSettingsShortcutsRouteImport } from './routes/_app/settings/shortcuts'
import { Route as AppSettingsPreferencesRouteImport } from './routes/_app/settings/preferences'
import { Route as AppSettingsDictationRouteImport } from './routes/_app/settings/dictation'
import { Route as AppSettingsAiModelsRouteImport } from './routes/_app/settings/ai-models'
import { Route as AppSettingsAdvancedRouteImport } from './routes/_app/settings/advanced'
import { Route as AppSettingsAboutRouteImport } from './routes/_app/settings/about'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app/notes.$noteId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesIndexRoute = AppNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNotesRoute,
} as any)
const AppSettingsVocabularyRoute = AppSettingsVocabularyRouteImport.update({
  id: '/settings/vocabulary',
  path: '/settings/vocabulary',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsSnippetsRoute = AppSettingsSnippetsRouteImport.update({
  id: '/settings/snippets',
  path: '/settings/snippets',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsShortcutsRoute = AppSettingsShortcutsRouteImport.update({
  id: '/settings/shortcuts',
  path: '/settings/shortcuts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsPreferencesRoute = AppSettingsPreferencesRouteImport.update({
  id: '/settings/preferences',
  path: '/settings/preferences',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsDictationRoute = AppSettingsDictationRouteImport.update({
  id: '/settings/dictation',
  path: '/settings/dictation',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsAiModelsRoute = AppSettingsAiModelsRouteImport.update({
  id: '/settings/ai-models',
  path: '/settings/ai-models',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsAdvancedRoute = AppSettingsAdvancedRouteImport.update({
  id: '/settings/advanced',
  path: '/settings/advanced',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsAboutRoute = AppSettingsAboutRouteImport.update({
  id: '/settings/about',
  path: '/settings/about',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => AppNotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof AppHistoryRoute
  '/notes': typeof AppNotesRouteWithChildren
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/settings/about': typeof AppSettingsAboutRoute
  '/settings/advanced': typeof AppSettingsAdvancedRoute
  '/settings/ai-models': typeof AppSettingsAiModelsRoute
  '/settings/dictation': typeof AppSettingsDictationRoute
  '/settings/preferences': typeof AppSettingsPreferencesRoute
  '/settings/shortcuts': typeof AppSettingsShortcutsRoute
  '/settings/snippets': typeof AppSettingsSnippetsRoute
  '/settings/vocabulary': typeof AppSettingsVocabularyRoute
  '/notes/': typeof AppNotesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof AppHistoryRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/settings/about': typeof AppSettingsAboutRoute
  '/settings/advanced': typeof AppSettingsAdvancedRoute
  '/settings/ai-models': typeof AppSettingsAiModelsRoute
  '/settings/dictation': typeof AppSettingsDictationRoute
  '/settings/preferences': typeof AppSettingsPreferencesRoute
  '/settings/shortcuts': typeof AppSettingsShortcutsRoute
  '/settings/snippets': typeof AppSettingsSnippetsRoute
  '/settings/vocabulary': typeof AppSettingsVocabularyRoute
  '/notes': typeof AppNotesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/history': typeof AppHistoryRoute
  '/_app/notes': typeof AppNotesRouteWithChildren
  '/_app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/_app/settings/about': typeof AppSettingsAboutRoute
  '/_app/settings/advanced': typeof AppSettingsAdvancedRoute
  '/_app/settings/ai-models': typeof AppSettingsAiModelsRoute
  '/_app/settings/dictation': typeof AppSettingsDictationRoute
  '/_app/settings/preferences': typeof AppSettingsPreferencesRoute
  '/_app/settings/shortcuts': typeof AppSettingsShortcutsRoute
  '/_app/settings/snippets': typeof AppSettingsSnippetsRoute
  '/_app/settings/vocabulary': typeof AppSettingsVocabularyRoute
  '/_app/notes/': typeof AppNotesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/notes'
    | '/notes/$noteId'
    | '/settings/about'
    | '/settings/advanced'
    | '/settings/ai-models'
    | '/settings/dictation'
    | '/settings/preferences'
    | '/settings/shortcuts'
    | '/settings/snippets'
    | '/settings/vocabulary'
    | '/notes/'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/notes/$noteId'
    | '/settings/about'
    | '/settings/advanced'
    | '/settings/ai-models'
    | '/settings/dictation'
    | '/settings/preferences'
    | '/settings/shortcuts'
    | '/settings/snippets'
    | '/settings/vocabulary'
    | '/notes'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/history'
    | '/_app/notes'
    | '/_app/notes/$noteId'
    | '/_app/settings/about'
    | '/_app/settings/advanced'
    | '/_app/settings/ai-models'
    | '/_app/settings/dictation'
    | '/_app/settings/preferences'
    | '/_app/settings/shortcuts'
    | '/_app/settings/snippets'
    | '/_app/settings/vocabulary'
    | '/_app/notes/'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notes/': {
      id: '/_app/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof AppNotesIndexRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/_app/settings/vocabulary': {
      id: '/_app/settings/vocabulary'
      path: '/settings/vocabulary'
      fullPath: '/settings/vocabulary'
      preLoaderRoute: typeof AppSettingsVocabularyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/snippets': {
      id: '/_app/settings/snippets'
      path: '/settings/snippets'
      fullPath: '/settings/snippets'
      preLoaderRoute: typeof AppSettingsSnippetsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/shortcuts': {
      id: '/_app/settings/shortcuts'
      path: '/settings/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof AppSettingsShortcutsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/preferences': {
      id: '/_app/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AppSettingsPreferencesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/dictation': {
      id: '/_app/settings/dictation'
      path: '/settings/dictation'
      fullPath: '/settings/dictation'
      preLoaderRoute: typeof AppSettingsDictationRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/ai-models': {
      id: '/_app/settings/ai-models'
      path: '/settings/ai-models'
      fullPath: '/settings/ai-models'
      preLoaderRoute: typeof AppSettingsAiModelsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/advanced': {
      id: '/_app/settings/advanced'
      path: '/settings/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof AppSettingsAdvancedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/about': {
      id: '/_app/settings/about'
      path: '/settings/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof AppSettingsAboutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notes/$noteId': {
      id: '/_app/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppNotesRoute
    }
  }
}

interface AppNotesRouteChildren {
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
}

const AppNotesRouteChildren: AppNotesRouteChildren = {
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
}

const AppNotesRouteWithChildren = AppNotesRoute._addFileChildren(
  AppNotesRouteChildren,
)

interface AppRouteRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppNotesRoute: typeof AppNotesRouteWithChildren
  AppSettingsAboutRoute: typeof AppSettingsAboutRoute
  AppSettingsAdvancedRoute: typeof AppSettingsAdvancedRoute
  AppSettingsAiModelsRoute: typeof AppSettingsAiModelsRoute
  AppSettingsDictationRoute: typeof AppSettingsDictationRoute
  AppSettingsPreferencesRoute: typeof AppSettingsPreferencesRoute
  AppSettingsShortcutsRoute: typeof AppSettingsShortcutsRoute
  AppSettingsSnippetsRoute: typeof AppSettingsSnippetsRoute
  AppSettingsVocabularyRoute: typeof AppSettingsVocabularyRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppNotesRoute: AppNotesRouteWithChildren,
  AppSettingsAboutRoute: AppSettingsAboutRoute,
  AppSettingsAdvancedRoute: AppSettingsAdvancedRoute,
  AppSettingsAiModelsRoute: AppSettingsAiModelsRoute,
  AppSettingsDictationRoute: AppSettingsDictationRoute,
  AppSettingsPreferencesRoute: AppSettingsPreferencesRoute,
  AppSettingsShortcutsRoute: AppSettingsShortcutsRoute,
  AppSettingsSnippetsRoute: AppSettingsSnippetsRoute,
  AppSettingsVocabularyRoute: AppSettingsVocabularyRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
