import { MAC_KEYCODES, WINDOWS_KEYCODES } from "./keycodes";

function expandReservedShortcuts(
  shortcuts: number[][],
  modifierPairs: [number, number][],
): number[][] {
  const pairMap = new Map<number, number>();
  for (const [left, right] of modifierPairs) {
    pairMap.set(left, right);
    pairMap.set(right, left);
  }

  const results: number[][] = [];
  const seen = new Set<string>();

  for (const shortcut of shortcuts) {
    let variants: number[][] = [[]];

    for (const key of shortcut) {
      const alternate = pairMap.get(key);
      if (alternate === undefined) {
        for (const variant of variants) {
          variant.push(key);
        }
        continue;
      }

      const next: number[][] = [];
      for (const variant of variants) {
        next.push([...variant, key]);
        next.push([...variant, alternate]);
      }
      variants = next;
    }

    for (const variant of variants) {
      const signature = [...variant].sort((a, b) => a - b).join(",");
      if (seen.has(signature)) continue;
      seen.add(signature);
      results.push(variant);
    }
  }

  return results;
}

export const MAC_MODIFIER_KEYCODES = new Set<number>([
  MAC_KEYCODES.CMD,
  MAC_KEYCODES.RCMD,
  MAC_KEYCODES.CTRL,
  MAC_KEYCODES.RCTRL,
  MAC_KEYCODES.ALT,
  MAC_KEYCODES.RALT,
  MAC_KEYCODES.SHIFT,
  MAC_KEYCODES.RSHIFT,
  MAC_KEYCODES.FN,
]);

export const WINDOWS_MODIFIER_KEYCODES = new Set<number>([
  WINDOWS_KEYCODES.WIN,
  WINDOWS_KEYCODES.RWIN,
  WINDOWS_KEYCODES.CTRL,
  WINDOWS_KEYCODES.RCTRL,
  WINDOWS_KEYCODES.ALT,
  WINDOWS_KEYCODES.RALT,
  WINDOWS_KEYCODES.SHIFT,
  WINDOWS_KEYCODES.RSHIFT,
]);

export const MAC_MODIFIER_PAIRS: [number, number][] = [
  [MAC_KEYCODES.SHIFT, MAC_KEYCODES.RSHIFT],
  [MAC_KEYCODES.CTRL, MAC_KEYCODES.RCTRL],
  [MAC_KEYCODES.ALT, MAC_KEYCODES.RALT],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.RCMD],
];

export const WINDOWS_MODIFIER_PAIRS: [number, number][] = [
  [WINDOWS_KEYCODES.SHIFT, WINDOWS_KEYCODES.RSHIFT],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.RCTRL],
  [WINDOWS_KEYCODES.ALT, WINDOWS_KEYCODES.RALT],
  [WINDOWS_KEYCODES.WIN, WINDOWS_KEYCODES.RWIN],
];

export const MAC_SPECIAL_KEYCODES = new Set<number>([
  MAC_KEYCODES.SPACE,
  MAC_KEYCODES.TAB,
  MAC_KEYCODES.ENTER,
  MAC_KEYCODES.ESCAPE,
  MAC_KEYCODES.DELETE,
  MAC_KEYCODES.FORWARD_DELETE,
  MAC_KEYCODES.UP,
  MAC_KEYCODES.DOWN,
  MAC_KEYCODES.LEFT,
  MAC_KEYCODES.RIGHT,
  MAC_KEYCODES.HOME,
  MAC_KEYCODES.END,
  MAC_KEYCODES.PAGE_UP,
  MAC_KEYCODES.PAGE_DOWN,
  MAC_KEYCODES.F1,
  MAC_KEYCODES.F2,
  MAC_KEYCODES.F3,
  MAC_KEYCODES.F4,
  MAC_KEYCODES.F5,
  MAC_KEYCODES.F6,
  MAC_KEYCODES.F7,
  MAC_KEYCODES.F8,
  MAC_KEYCODES.F9,
  MAC_KEYCODES.F10,
  MAC_KEYCODES.F11,
  MAC_KEYCODES.F12,
  MAC_KEYCODES.F13,
  MAC_KEYCODES.F14,
  MAC_KEYCODES.F15,
  MAC_KEYCODES.F16,
  MAC_KEYCODES.F17,
  MAC_KEYCODES.F18,
  MAC_KEYCODES.F19,
  MAC_KEYCODES.F20,
]);

export const WINDOWS_SPECIAL_KEYCODES = new Set<number>([
  WINDOWS_KEYCODES.SPACE,
  WINDOWS_KEYCODES.TAB,
  WINDOWS_KEYCODES.ENTER,
  WINDOWS_KEYCODES.ESCAPE,
  WINDOWS_KEYCODES.DELETE,
  WINDOWS_KEYCODES.BACKSPACE,
  WINDOWS_KEYCODES.UP,
  WINDOWS_KEYCODES.DOWN,
  WINDOWS_KEYCODES.LEFT,
  WINDOWS_KEYCODES.RIGHT,
  WINDOWS_KEYCODES.HOME,
  WINDOWS_KEYCODES.END,
  WINDOWS_KEYCODES.PAGE_UP,
  WINDOWS_KEYCODES.PAGE_DOWN,
  WINDOWS_KEYCODES.INSERT,
  WINDOWS_KEYCODES.F1,
  WINDOWS_KEYCODES.F2,
  WINDOWS_KEYCODES.F3,
  WINDOWS_KEYCODES.F4,
  WINDOWS_KEYCODES.F5,
  WINDOWS_KEYCODES.F6,
  WINDOWS_KEYCODES.F7,
  WINDOWS_KEYCODES.F8,
  WINDOWS_KEYCODES.F9,
  WINDOWS_KEYCODES.F10,
  WINDOWS_KEYCODES.F11,
  WINDOWS_KEYCODES.F12,
  WINDOWS_KEYCODES.F13,
  WINDOWS_KEYCODES.F14,
  WINDOWS_KEYCODES.F15,
  WINDOWS_KEYCODES.F16,
  WINDOWS_KEYCODES.F17,
  WINDOWS_KEYCODES.F18,
  WINDOWS_KEYCODES.F19,
  WINDOWS_KEYCODES.F20,
  WINDOWS_KEYCODES.F21,
  WINDOWS_KEYCODES.F22,
  WINDOWS_KEYCODES.F23,
  WINDOWS_KEYCODES.F24,
]);

const RESERVED_SHORTCUTS_MACOS_BASE: number[][] = [
  // Clipboard
  [MAC_KEYCODES.CMD, MAC_KEYCODES.C],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.V],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.X],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.Z],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.SHIFT, MAC_KEYCODES.Z],
  // Window/App management
  [MAC_KEYCODES.CMD, MAC_KEYCODES.Q],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.W],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.M],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.H],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.TAB],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.SPACE],
  // Screenshots
  [MAC_KEYCODES.CMD, MAC_KEYCODES.SHIFT, MAC_KEYCODES.THREE],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.SHIFT, MAC_KEYCODES.FOUR],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.SHIFT, MAC_KEYCODES.FIVE],
  // Mission Control
  [MAC_KEYCODES.CTRL, MAC_KEYCODES.UP],
  [MAC_KEYCODES.CTRL, MAC_KEYCODES.DOWN],
  [MAC_KEYCODES.CTRL, MAC_KEYCODES.LEFT],
  [MAC_KEYCODES.CTRL, MAC_KEYCODES.RIGHT],
  // File operations
  [MAC_KEYCODES.CMD, MAC_KEYCODES.N],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.O],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.S],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.P],
  // Edit
  [MAC_KEYCODES.CMD, MAC_KEYCODES.A],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.F],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.G],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.SHIFT, MAC_KEYCODES.G],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.R],
  // Text formatting
  [MAC_KEYCODES.CMD, MAC_KEYCODES.B],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.I],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.U],
  // Navigation
  [MAC_KEYCODES.CMD, MAC_KEYCODES.LEFT],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.RIGHT],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.UP],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.DOWN],
  // Selection
  [MAC_KEYCODES.CMD, MAC_KEYCODES.SHIFT, MAC_KEYCODES.LEFT],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.SHIFT, MAC_KEYCODES.RIGHT],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.SHIFT, MAC_KEYCODES.UP],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.SHIFT, MAC_KEYCODES.DOWN],
  // System
  [MAC_KEYCODES.CMD, MAC_KEYCODES.ALT, MAC_KEYCODES.ESCAPE],
  // Delete
  [MAC_KEYCODES.CMD, MAC_KEYCODES.DELETE],
  [MAC_KEYCODES.ALT, MAC_KEYCODES.DELETE],
  // Tabs
  [MAC_KEYCODES.CMD, MAC_KEYCODES.T],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.SHIFT, MAC_KEYCODES.T],
  // Zoom
  [MAC_KEYCODES.CMD, MAC_KEYCODES.EQUAL],
  [MAC_KEYCODES.CMD, MAC_KEYCODES.MINUS],
  // Other common
  [MAC_KEYCODES.CMD, MAC_KEYCODES.COMMA],
];

const RESERVED_SHORTCUTS_WINDOWS_BASE: number[][] = [
  // Clipboard
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.C],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.V],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.X],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.Z],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.Y],
  // Window/App management
  [WINDOWS_KEYCODES.ALT, WINDOWS_KEYCODES.TAB],
  [WINDOWS_KEYCODES.ALT, WINDOWS_KEYCODES.F4],
  [WINDOWS_KEYCODES.F11],
  // File operations
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.N],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.O],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.S],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.P],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.T],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.W],
  // Edit
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.A],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.F],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.G],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.R],
  [WINDOWS_KEYCODES.F5],
  // Text formatting
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.B],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.I],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.U],
  // Navigation
  [WINDOWS_KEYCODES.HOME],
  [WINDOWS_KEYCODES.END],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.HOME],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.END],
  [WINDOWS_KEYCODES.ALT, WINDOWS_KEYCODES.LEFT],
  [WINDOWS_KEYCODES.ALT, WINDOWS_KEYCODES.RIGHT],
  // Selection
  [WINDOWS_KEYCODES.SHIFT, WINDOWS_KEYCODES.HOME],
  [WINDOWS_KEYCODES.SHIFT, WINDOWS_KEYCODES.END],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.SHIFT, WINDOWS_KEYCODES.HOME],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.SHIFT, WINDOWS_KEYCODES.END],
  // System
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.ALT, WINDOWS_KEYCODES.DELETE],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.SHIFT, WINDOWS_KEYCODES.ESCAPE],
  // Windows key shortcuts
  [WINDOWS_KEYCODES.WIN, WINDOWS_KEYCODES.E],
  [WINDOWS_KEYCODES.WIN, WINDOWS_KEYCODES.R],
  [WINDOWS_KEYCODES.WIN, WINDOWS_KEYCODES.L],
  [WINDOWS_KEYCODES.WIN, WINDOWS_KEYCODES.D],
  [WINDOWS_KEYCODES.WIN, WINDOWS_KEYCODES.TAB],
  [WINDOWS_KEYCODES.WIN, WINDOWS_KEYCODES.I],
  [WINDOWS_KEYCODES.WIN, WINDOWS_KEYCODES.S],
  [WINDOWS_KEYCODES.WIN, WINDOWS_KEYCODES.X],
  [WINDOWS_KEYCODES.WIN, WINDOWS_KEYCODES.P],
  [WINDOWS_KEYCODES.WIN, WINDOWS_KEYCODES.UP],
  [WINDOWS_KEYCODES.WIN, WINDOWS_KEYCODES.DOWN],
  [WINDOWS_KEYCODES.WIN, WINDOWS_KEYCODES.Q],
  // Delete
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.BACKSPACE],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.DELETE],
  // Tabs
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.SHIFT, WINDOWS_KEYCODES.T],
  // Zoom
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.EQUAL],
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.MINUS],
  // Other
  [WINDOWS_KEYCODES.CTRL, WINDOWS_KEYCODES.K],
];

export const RESERVED_SHORTCUTS_MACOS = expandReservedShortcuts(
  RESERVED_SHORTCUTS_MACOS_BASE,
  MAC_MODIFIER_PAIRS,
);

export const RESERVED_SHORTCUTS_WINDOWS = expandReservedShortcuts(
  RESERVED_SHORTCUTS_WINDOWS_BASE,
  WINDOWS_MODIFIER_PAIRS,
);
